### ISSUE TITLE
Ride route image links broken

### ISSUE THREAD

**Issue by rniemela77** [jordanpartridge/jordanpartridge.us#66]
Your website is looking really cool Jordan!

I'm going to make a little CSS effect in a PR that you can add to your bike page if you want.
I saw some broken image links so I thought I'd crete an issue.

<img width="400" alt="image" src="https://github.com/user-attachments/assets/df1654a7-19ec-4c88-b0c7-6d4b1e4e49e2">

When I try to open image in new tab,
> The Google Maps Platform server rejected your request. You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started

**Comment by jordanpartridge** [comment]
thanks for pointing that out I wasn't aware but I have some ideas

**Comment by jordanpartridge** [comment]
I have a temporary fix by adding billing info, however I want to work in this more and save the images so they only need to be generated once.

**Comment by jordanpartridge** [comment]
Moved to s3 storage in a previous PR this is complete.
